version: 1

triggers:
  location:
    latitude: 45.520282
    longitude: -122.632316
    #latitude: 40.689412062832226
    #longitude: -74.0444896661189
  aqi:
    # https://docs.airnowapi.org/
    api_key: ${env:AQI_API_KEY}

providers:
  gosund:
    username: ${env:GOSUND_USERNAME}
    password: ${env:GOSUND_PASSWORD}
    access_id: ${env:GOSUND_ACCESS_ID}
    access_key: ${env:GOSUND_ACCESS_KEY}
  noop:

devices:
  switch-A:
    description: air purifier
    provider: noop
    type: switch
    id: '3460050570039f61e488'
  bulb-A:
    description: party light
    provider: noop
    type: light-bulb
    id: 'eb46f5bc889a96fe4ecray'
  bulb-B:
    description: floor lamp 1
    provider: noop
    type: light-bulb
    id: '123abc'
  bulb-C:
    description: floor lamp 2
    provider: noop
    type: light-bulb
    id: 'abc123'

automations:
  air-purifier:
    enabled: true
    components:
      - if:
          aqi: < 100
        then:
          turn-off: switch-A
        else:
          turn-on: switch-A

  party-light:
    enabled: true
    components:
      - if:
          weekday: friday,saturday
          time: 3:00pm
        then:
          turn-on: bulb-A
      - if:
          weekday: friday,saturday
          time: 8:00pm
        then:
          turn-off: bulb-A

  floor-lamp:
    enabled: true
    components:
      # turn on
      - if:
          sunset: -2:00
        then:
          turn-on: bulb-B
      - if:
          time: 5:00pm
        then:
          turn-on: bulb-B, bulb-C
      # turn off weeknights
      - if:
          weekday: sunday,monday,tuesday,wednesday,thursday
          time: 8:00pm
        then:
          turn-off: bulb-B
      - if:
          weekday: sunday,monday,tuesday,wednesday,thursday
          time: 9:00pm
        then:
          turn-off: bulb-C
      # turn off weekends
      - if:
          weekday: friday,saturday
          time: 9:00pm
        then:
          turn-off: bulb-B
      - if:
          weekday: friday,saturday
          time: 10:00pm
        then:
          turn-off: bulb-C
